class Api::V1::CreditCardsController < Api::BaseController
  before_action :authenticate_user!

  resource_description do
    short 'Credit card for users'
  end

  api! 'Create credit card for user'
  description <<-EOS
    ## Description
    Create credit card with stripe card token.
    Returns created card
  EOS
  param :stroke_token, String, desc: 'Stripe token generated by Stripe.js'
  def create
    @card = stripe_manager.create_credit_card(card_params[:card_token])
    respond_with :api, :v1, @card
  end

  api! 'Update default credit card for user'
  description <<-EOS
    ## Description
    Update user's default credit card.
    Returns empty body.
  EOS
  param :id, Integer, desc: 'Credit card id'
  def make_default
    stripe_manager.change_default_create_card(params[:id])
    @cards = current_user.credit_cards
    respond_with :api, :v1, @cards
  end

  private

  def stripe_manager
    @user_stripe_manager ||= ManageUserStripe.new(current_user)
  end

  def card_params
    params.require(:credit_card).permit(:card_token)
  end

end